# Generated by Django 5.2.5 on 2025-10-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_color_color_code_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
