# Generated by Django 5.2.5 on 2025-12-05 13:08

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix=''),
        ),
    ]
